### ISSUE TITLE
api: rework todo.

### ISSUE THREAD

**Issue by Ganom** [Ganom/Supporter-Issue-Tracker#241]
Pathing:
- [x] Cache pathing calculations to reduce CPU load.
- [x] Retry pathing if it fails instead of entering critical fail state.
- [x] Reduce CPU intense distance calculations.

Banking:
- [ ] (Maybe) Validate withdraw before opening
- [x] Find out what's causing withdraws to fail.

Plugins:
- [x] Blast Furnace (Banking)
- [x] Agility (Pathing)
- [x] Thieving (Pathing & Banking)
- [ ] Wintertodt (Pathing & Banking)
- [x] Runecrafter (Banking & Colossal support)
